<?
    /** @var \Sb\Phalcon\Helpers\UrlHelper $url */
    /** @var \Sb\Phalcon\Helpers\SeoHelper $seo */
?>
<!DOCTYPE html>

<html lang="ru" <?= $seo->renderHtmlPrefix()?>>
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />

    <?= $seo->render() ?>

</head>
<body>
    <div class="container">
        <?= $this->getContent() ?>
    </div>
</body>
</html>
